language: node_js

node_js:
  - lts/*

os: linux

dist: focal

services:
  - docker

addons:
  apt:
    packages:
      - libgconf-2-4

cache:
  yarn: true
  directories:
    - ~/.cache

branches:
  only:
    - main

script:
  - yarn test --ci
  - NEXT_PUBLIC_FORCE_DEFAULT_THEME=light yarn build
  - yarn start & wait-on http://localhost:3000
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ];
    then
      yarn cy:run --record --key $CY_KEY;
    else
      yarn cy:run;
    fi'

before_deploy:
  - mkdir -vp ~/.docker/cli-plugins/
  - curl --silent -L "https://github.com/docker/buildx/releases/download/v0.8.2/buildx-v0.8.2.linux-amd64" > ~/.docker/cli-plugins/docker-buildx
  - chmod a+x ~/.docker/cli-plugins/docker-buildx
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker buildx create --use

deploy:
  provider: script
  script: docker buildx build --push
    --platform linux/amd64,linux/arm/v7,linux/arm64/v8
    --tag thedaviddelta/lingva-translate .
  on:
    branch: main
